version: 2

sources:
  - name: jaffle_shop
    database: raw
    schema: jaffle_shop
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: "CAST(order_date AS TIMESTAMP)"

    tables:
      - name: orders

      - name: customers
        freshness: null # do not check freshness for this table
        
  - name: stripe
    database: raw
    schema: stripe

    tables:
      - name: payment
        freshness: null # do not check freshness for this table